### ISSUE TITLE
module pg.js is not found

### ISSUE THREAD

**Issue by dmitriiabramov** [voxpelli/node-connect-pg-simple#12]
as i see in the recent commits `pg.js` was replaced with `pg`
but in the code there is still a reference to `pg.js` which breaks the code
https://github.com/voxpelli/node-connect-pg-simple/blob/master/index.js#L17

**Comment by voxpelli** [comment]
Thanks for reporting this! Such an embarrassing mistake.

I guess all the projects I tested the new release in was using `pg.js` or something so didn't notice it, so as a follow up I will try to find a dependency linter/checker to automate checks for this.

I've released 2.2.1 that fixes this.
