### ISSUE TITLE
Set session only if login - passport

### ISSUE THREAD

**Issue by richlewis14** [voxpelli/node-connect-pg-simple#131]
Hi

Firstly thank you for taking the time to put this out there and maintain it. I had a question around only saving a session if a user logs in (currently use passport). This is my config so far

    // server.js
    app.use(session({
      store: new PGSession({
      pool: dbConn, // Connection pool
    }),
      secret: 'secret-here',
      name: 'session',
      resave: false,
      saveUninitialized: false,
      secure: true,
      cookie: { maxAge: 365 * 24 * 60 * 60 * 1000 },
    }));
    app.use(passport.initialize());
    app.use(passport.session());

What I notice so far is that for when ever someone accesses the site and entry is made like so

    123456789,"{""cookie"":{""originalMaxAge"":31536000000,""expires"":""2020-04-13T09:55:11.015Z"",""httpOnly"":true,""path"":""/""},""flash"":{}}",2020-04-13 09:55:12.000000

When someone logs in their user id gets attached like so

    1234567,"{""cookie"":{""originalMaxAge"":31536000000,""expires"":""2020-04-10T20:10:07.241Z"",""httpOnly"":true,""path"":""/""},""flash"":{},""passport"":{""user"":12345}}",2020-04-10 20:19:43.000000

Is there a way to set this up so a session only gets stored if logged in

Thanks

**Comment by unknowndomain** [comment]
Rich, 

This isn't an issue with the session store, or passport.js but with your flash plugin which creates an empty object and saves it, if you have a look at creativetechnologylab/express-flash I pulled in @onnlucky's patch for this.

The fix is line 30: https://github.com/creativetechnologylab/express-flash/blob/master/lib/express-flash.js

**Comment by richlewis14** [comment]
Thank you very much, solved the issue straight away by switching out connect-flash for express-flash. Cannot thank you enough

**Comment by richlewis14** [comment]
Have pushed this live now but still getting empty objects (When testing locally I could would not get empty objects, hence my above comment). Are there any circumstances where this could still be happening ?

**Comment by unknowndomain** [comment]
You have to do that test around every use of req.flash()

**Comment by voxpelli** [comment]
Happy that seems to have solved itself, I'll close it then 🥇
