### ISSUE TITLE
add an option to automatically create table if not present

### ISSUE THREAD

**Issue by towc** [voxpelli/node-connect-pg-simple#158]
I came here because of issues with https://github.com/llambda/connect-session-knex

That library had a really handy `createtable` option that you could use instead of creating the table yourself.

This is great for setups like mine, that involve an unmodified pg docker container, and a node container that installs npm plugins and calls a js script.

One consideration to have for adding the feature is that the script might be updated, but someone forgets to update the sql file, or vice versa. I don't know much about postgres, but getting the sql file as text and sending it as a raw query to the server would work, right? This way, there's a single source for creating the table

**Comment by voxpelli** [comment]
Makes sense, would you like to make an attempt at a PR?

**Comment by towc** [comment]
not in the next couple of weeks :/
