### ISSUE TITLE
errorToCallbackAndReject() is never passed a callback function

### ISSUE THREAD

**Issue by alxndrsn** [voxpelli/node-connect-pg-simple#180]
[`errorToCallbackAndReject()`](https://github.com/voxpelli/node-connect-pg-simple/blob/7683d4004664ecb9b1615e151249f88271d8b111/index.js#L36) accepts two arguments:

https://github.com/voxpelli/node-connect-pg-simple/blob/7683d4004664ecb9b1615e151249f88271d8b111/index.js#L36-L39

but it's only ever called at https://github.com/voxpelli/node-connect-pg-simple/blob/7683d4004664ecb9b1615e151249f88271d8b111/index.js#L263, where it's passed 1 argument.

PR at https://github.com/voxpelli/node-connect-pg-simple/pull/179 may address this issue.

**Comment by voxpelli** [comment]
Thanks, I’ll check soon when I’m at a computer
