### ISSUE TITLE
Connection to postgres hangs

### ISSUE THREAD

**Issue by dustin-auby** [voxpelli/node-connect-pg-simple#182]
Hi,

We have implemented connect-pg-simple and it works on some servers but seems to hang on others. we have tested on a google cloud app engine and it also hangs there. it eventually throws a timeout exception. i am running node.js v14.1.0. and postgres v12.3 and it hangs for me where another pc right next to me is running node.js v12 and postgre 12.3 and it works for them. we are running express-session with  nuxt

Any assistance would be appreciated.

**Comment by voxpelli** [comment]
Which version of this module are you using? Version 6.2.0 and later should work well with Node 14 and the test suite are run across all supported node.js versions as well as many postgres versions (maybe I haven't added the very latest Postgres yet)

If you can verify whether you are indeed using the latest version of the module, then we can try to figure out the reason why it still might not work for you

**Comment by dustin-auby** [comment]
Hi,

I managed to resolve the problem. it was actually the node-postgres and the nodejs 14 that were conflicting. once i moved back to nodejs 12 it worked fine.
