### ISSUE TITLE
Missing callback parameter of close method

### ISSUE THREAD

**Issue by pphunor** [voxpelli/node-connect-pg-simple#183]
Close method is asynchronous, at least when this.ownsPg is true. Calling this.pool.end() without a callback parameter makes it impossible to detect the end of the process. A minor code change can fix it, like below:
> 
	close (cb) {
		this.closed = true;
		...
		if (this.ownsPg) {
			this.pool.end(cb);
		} else {
			process.nextTick(cb.bind(this, null));
		}
	}

**Comment by voxpelli** [comment]
Makes sense @pphunor, maybe we could even use `async` / `await` for this? Make the close method async?

PR is welcome 👍
