### ISSUE TITLE
session table for TypeORM+TypeGraphQL

### ISSUE THREAD

**Issue by JarLowrey** [voxpelli/node-connect-pg-simple#184]
Just wanted to confirm this is the right session  table for typeorm and typeGraphql. I don't know if the session even needs to be registered with TypeGraphQL, but if so it doesn't appear to have a JSON field. Is there a TS definition of the session object I can put there instead? Also, what should be used for sid collation?

Session sql for reference: https://github.com/voxpelli/node-connect-pg-simple/blob/HEAD/table.sql

```

@Entity() // TypeGraphQL
@ObjectType()
export class session {
    @Field() // TypeGraphQL
    @PrimaryColumn({
        type: "varchar",
        nullable: false,
        //collation:"" //needed?
    })
    sid:string;

    //@Field() // TypeGraphQL doesnt like json types...is this needed?
    @Column({
        type: "json",
        nullable: false
    })
    sess:any;

    @Field() // TypeGraphQL
    @Index("IDX_session_expire")
    @Column({
        type: "timestamp",
        precision: 6,
        nullable: false
    })
    expire:Date;
}
```

**Comment by voxpelli** [comment]
>  I don't know if the session even needs to be registered with TypeGraphQL

As the session table is for internal use of this module, I can't really se the need for marking it up for this @JarLowrey 🤔

Reason why TypeGraphQL doesn't like JSON columns is probably that GraphQL doesn't like arbitrary objects, it requires that all objects are clearly defined.

My suggestion would be: Skip exposing the table in TypeGraphQL. What do you think?

**Comment by JarLowrey** [comment]
I'd agree that it is probably unnecessary, just wasn't sure how this was setup in the back end. How about sid collation, any opinions there? Thank you!

**Comment by voxpelli** [comment]
I'm not sure I can give any meaningful feedback on TypeORM/TypeGraphQL – never used them – so unfortunately going to close for now 😢
