### ISSUE TITLE
Please implement length

### ISSUE THREAD

**Issue by nirko-rnd** [voxpelli/node-connect-pg-simple#186]
It can be useful to implement the optional [store.length(callback)](https://www.npmjs.com/package/express-session#storelengthcallback)

**Comment by voxpelli** [comment]
Sure, that can be added, is there any specific use case for it @nirko-rnd?

**Comment by nirko-rnd** [comment]
An admin want to count the number of concurrent sessions

**Comment by voxpelli** [comment]
An admin can do that in Postgres directly, right?

Or is there any tool that makes use of this feature in session plugins?

**Comment by nirko-rnd** [comment]
Sure, We can expose a query from the DB. but when I saw that it's an optional function I thought it might be better to implement it through this package

**Comment by voxpelli** [comment]
I just wonder where it would be used in actual code? If express-session itself is going to use it, then it might give some performance impact if it queries the length often 🤔 Since its an actual part of the plugin interface, the intent isn't really for anyone else but express-session to use it?

**Comment by nirko-rnd** [comment]
Ok, i can see your point.
Thanks
