### ISSUE TITLE
Callback passed to destroy(sid, fn) is overwritten by the sid.

### ISSUE THREAD

**Issue by saraginov** [voxpelli/node-connect-pg-simple#188]
System:
psql (PostgreSQL) 13.1 (Ubuntu 13.1-1.pgdg20.04+1)
nvm --version
0.35.1
nvm ls
->     v14.15.1
default -> 14.15.1 (-> v14.15.1)
node -> 14.15.1 (-> v14.15.1)
stable -> 14.15.1 (-> v14.15.1)

---
package-lock.json:

"connect-pg-simple": {
  "version": "6.2.1",
  "resolved": "https://registry.npmjs.org/connect-pg-simple/-/connect-pg-simple-6.2.1.tgz",
  "integrity": "sha512-bwDp/gKyRtyz0V5Vxy3SATSxItWBK/wDhaacncC79+q1B1VB8SQ49AlVaQCM+XxmIO29cWX4cvsFj65mD2qrzA==",
  "requires": {
    "@types/pg": "^7.14.4",
    "pg": "^8.2.1"
  }
},

---
CLI warning:

(node:22756) UnhandledPromiseRejectionWarning: TypeError: fn is not a function\
    at /path/to/project/node_modules/connect-pg-simple/index.js:303:24
    at /path/to/project/node_modules/connect-pg-simple/index.js:238:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:22756) TypeError: fn is not a function
    at /path/to/project/node_modules/connect-pg-simple/index.js:303:24
    at /path/to/project/node_modules/connect-pg-simple/index.js:238:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:22756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

---
In app.js:

const pgStore = require('connect-pg-simple');
const pgSession = pgStore(session);

const storeInitOptions = {
  pgPromise: db,  // imported instance of pg-promise
  tableName: 'session',
  schemaName: 'public',
  createTableIfMissing: true,
};

app.use(session({
  store: new pgSession(storeInitOptions),
  resave: false,
  saveUninitialized: false,
  secret: SESS_SECRET,
  rolling: true,
  cookie: {
    name: SESS_NAME,
    maxAge: SESS_LIFETIME,
    sameSite: true,
    secure: IN_PROD,
  },
}));

---
In controller.js:

exports.logOut = async function(req, res)
{
  const {session, sessionID} = req;
  
  const cb = (err) => {
    console.log({err});
  }

  console.log({sessionID});
  console.log(cb);

  const deletedSession = await req.session.destroy(sessionID, cb);
  // I also tried without async/await and got the same results
  
  res.header('Content-Type', 'application/json;charset=UTF-8');
  res.header('Access-Control-Allow-Credentials', true);
  res.header(
    'Access-Control-Allow-Headers',
    'Origin, X-Requested-With, Content-Type, Accept'
  );

  req.session = null;
  res.end('Logged Out');
}

The console.log in logOut:
{ sid: 'aa-bbbb_ccccccccccccc-dddddddddd' }
[Function: cb]

index.js line 297(of connect-pg-simple) I added :
console.log({sid});
console.log(fn);

and when I invoke logOut, sid is used as fn in destroy (sid, fn) :

{ sid: 'aa-bbbb_ccccccccccccc-dddddddddd' }
aa-bbbb_ccccccccccccc-dddddddddd

---
Let me know if you require any additional information, thanks in advance.

**Comment by makuga01** [comment]
Hey @saraginov! How did you manage to solve this?

**Comment by saraginov** [comment]
@makuga01 I didn't, I closed this because I am overwhelmed with other work and don't have time to address it. Feel free to re-open it if you would like.

**Comment by makuga01** [comment]
@saraginov I actually found the solution lol
I dug into source of `req.session.destroy` -> found out that it takes only the `fn` argument and later passes it to `req.sessionStore.destroy(this.id, fn)` 
## The solution in your case would be just to do 

```js
exports.logOut = async function(req, res)
{
const {session, sessionID} = req;

const cb = (err) => {
console.log({err});
}

console.log({sessionID});
console.log(cb);

const deletedSession = req.sessionStore.destroy(sessionID, cb);

res.header('Content-Type', 'application/json;charset=UTF-8');
res.header('Access-Control-Allow-Credentials', true);
res.header(
'Access-Control-Allow-Headers',
'Origin, X-Requested-With, Content-Type, Accept'
);

delete req.session
res.end('Logged Out');
}
```

## Or a little better without using the `session.destroy`

```js
req.session.destroy(function (err: Error) {
    if (err) {
      res.status(400)
    } else {
      res.clearCookie('connect.sid')
      res.header('Content-Type', 'application/json;charset=UTF-8');
      res.header('Access-Control-Allow-Credentials', true);
      res.header(
      'Access-Control-Allow-Headers',
      'Origin, X-Requested-With, Content-Type, Accept'
      );
      res.status(200)
    }
  })
```

## Bonus

The `connect-pg-simple` module just runs a simple SQL query when `sessionStore.destroy(x, y)` is called.

```sql
this.query(
        'DELETE FROM ' + this.quotedTable() + ' WHERE sid = $1',
        [sid],
        err => { fn && fn(err); }
      );
```

My usecase of this was to log user off on every device using a knex/sql query like this

```js
knex('session').select('sid').whereRaw("sess->'passport'->>'user' = ?", [userId]).delete()
```

```sql
select sess->'passport'->>'user' as userid from session where sess->'passport'->>'user' = 'ID here'
```

**Comment by saraginov** [comment]
Thank you I appreciate it, I will try it out at some point soon and get back to you.

**Comment by makuga01** [comment]
Glad to help
