### ISSUE TITLE
Invalid DB logic

### ISSUE THREAD

**Issue by vitaly-t** [voxpelli/node-connect-pg-simple#19]
Line 127:
```javascript
if (fn) { fn(err, result && result.rows[0] ? result.rows[0] : false); }
```
`result` in that context is non-null even when 0 rows are returned, so your code will throw an exception trying to access `result.rows[0]` in that case.

**Comment by voxpelli** [comment]
But when 0 rows are returned, aren't `.rows` then just an empty array rather than undefined?

**Comment by vitaly-t** [comment]
Your code should be:

```javascript
if (fn) {
    fn(err, (result && result.rows.length) ? result.rows[0] : false);
}
```

**Comment by voxpelli** [comment]
@vitaly-t: Are you actually running in to an issue with this?

Requesting a non-existing index of an array should not throw an exception. Try eg. `console.log([][0])` – it will return `undefined` which will evaluate to `false` in the if-statement and thus should work the same as your suggestion.

**Comment by vitaly-t** [comment]
I'm not running into an issue with this myself, I just do a lot of development around postgres, so enjoy being a pain in the meantime :)
