### ISSUE TITLE
tableName : 'user_sessions'  vs CREATE TABLE "session"

### ISSUE THREAD

**Issue by PrimeLens** [voxpelli/node-connect-pg-simple#20]
Just a minor thing I noticed.  In table.sql  the table name is "session"

but in the read me you wrote

store: new pgSession({
    pg : pg,
    conString : process.env.FOO_DATABASE_URL,
    tableName : 'user_sessions'
  }),

should be 

store: new pgSession({
    pg : pg,
    conString : process.env.FOO_DATABASE_URL,
    tableName : 'session'
  }),

Great work tho, thanks for this repo

**Comment by voxpelli** [comment]
The point of the advanced example is to show that the table name can be configured to something else than the default, so the non-default schema name is intentional but that should perhaps be clarified by a code comment in the readme or so.
