### ISSUE TITLE
Error thrown when setting a session when connecting to Heroku-hosted PostgreSQL

### ISSUE THREAD

**Issue by nstuyvesant** [voxpelli/node-connect-pg-simple#201]
Getting this error when defining a session store using connect-pg-simple (6.2.1 or 7.0.0-0 - no difference)...

> error: no pg_hba.conf entry for host "IP_ADDRESS", user "USER", database "DATABASE", SSL off

```javascript
import dotenv from 'dotenv'
import pg from 'pg'
import session from 'express-session'
import ConnectPgSimple from 'connect-pg-simple'

const result = dotenv.config()
const { Client, native } = pg

const pgNativePool = new native.Pool({
  max: 10, // default
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
})

// Block that throws error
const pgSession = new ConnectPgSimple(session);
const store = new pgSession({
  pgNativePool,
  tableName: 'sessions'
})

export default {
  query: (sql, params) => pgNativePool.query(sql, params),
  store
}
```

If I comment out the block where I define pgSession, the error goes away. Heroku requires SSL to connect to their PostgreSQL databases. I thought connect-pg-simple would reuse the native connection pool I passed to it. I also tried using a non-native Pool but still got the error.

Any thoughts?

**Comment by nstuyvesant** [comment]
ugh... left out "pool:" Sorry, my mistake.

**Comment by voxpelli** [comment]
No worries! Had this exact issue myself yesterday: https://twitter.com/voxpelli/status/1371799296912322563
