### ISSUE TITLE
relax restrictions on engine 0.10.X

### ISSUE THREAD

**Issue by nmccready** [voxpelli/node-connect-pg-simple#22]
Can we make this support `>=0.10.X <0.13` ? I can PR it. 

Looking to get rid of warnings.

**Comment by voxpelli** [comment]
Where do you get warnings? I was under the impression that the engine field was more or less deprecated now a days?

**Comment by nmccready** [comment]
On node 0.12.4 and npm 2.11.0

**Comment by voxpelli** [comment]
So npm is warning you on install time? Should update the definition then. Thanks for pointing it out!

**Comment by nmccready** [comment]
Oh yeah add iojs as well please :)

**Comment by nmccready** [comment]
```
  "engines": {
    "node": ">=0.8 <0.13 || >=1 <=2",
    "iojs": ">=1 <3"
  },
```
