### ISSUE TITLE
Use ES6 import

### ISSUE THREAD

**Issue by richlewis14** [voxpelli/node-connect-pg-simple#224]
Hi

Previously I have used

    const PGSession = require('connect-pg-simple')(session);

Was just wondering if we can use this using an ES6 import statement?

    import PGSession from "connect-pg-simple"
    
Not sure how to include the (session) part though?

Any advice appreciated, thank you

**Comment by richlewis14** [comment]
Just an update, managed to get it working with

    import PGSimple from 'connect-pg-simple'
    const PGSession = PGSimple(session)
    
May help someone else if they have the same question

**Comment by voxpelli** [comment]
Great! I'll eventually update the README to include examples of this (PR:s welcome) and also at some point probably this project to itself use ESM 👍

**Comment by davidkhierl** [comment]
Hi, I'm getting this typescript error
![image](https://user-images.githubusercontent.com/25083033/197862776-f3e24856-7ad1-4414-98b9-000d1e031de7.png)

I'm using redis before and decided to migrate to this, when using redis similar approach without typescript error
