### ISSUE TITLE
Change `pg` to a peer dependency

### ISSUE THREAD

**Issue by thernstig** [voxpelli/node-connect-pg-simple#227]
Currenly `pg` is configured as a dependency of this project:

https://github.com/voxpelli/node-connect-pg-simple/blob/fdfcda883f0f730a3ee8e56d6e2d717e442d2f7d/package.json#L16-L19

Would it not be more correct to install this as a peerDependency? With npm 7 peer dependencies are also installed by default.

**Comment by voxpelli** [comment]
I don't think it would add much to do that change and its not strictly more correct. Only slight benefit would be to be able to indicate unsupported versions of `pg` 🤔 

I'll think about it + lets other weigh in on it.

**Comment by voxpelli** [comment]
I currently see no need for this change and no one else has weighed in over a year.

I'm still open to having a discussion of some feel strongly about this in either direction.
