### ISSUE TITLE
'Failed to prune sessions: con.connect is not a function' when trying to connect PostgreSQL database with session store via Knex.js

### ISSUE THREAD

**Issue by A-PS1999** [voxpelli/node-connect-pg-simple#247]
I am making a website and I'm trying to use Knex.js, express-session, connect-pg-simple and a postgreSQL database for the back end. For some reason, when I run my server I get this message in the console:

`Failed to prune session: con.connect is not a function`

This message is definitely related to my session store as when I remove the code for the session store it doesn't give me this message. I don't know why I get this message though, as I don't actually use `con.connect` in any of the code I have typed out.
Sorry if this isn't the right place for this but I thought it must be related to either connect-pg-simple or express-session. There also doesn't appear to be much about this elsewhere online.

Here is what my session store looks like:

```javascript
    const path = require('path');
    const dbCon = require('../../knexfile');
    require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env.development') });
    const express_session = require('express-session');
    const pgSession = require('connect-pg-simple')(express_session);

    const theSecret = process.env.VITE_SESSION_SECRET;

    const session = express_session({
        store: new pgSession({ tableName: 'sessions', conObject: dbCon }),
        secret: theSecret,
        resave: false,
        saveUninitialized: false,
        cookie: { maxAge: 1000 * 60 * 60 * 24 },
    })

    module.exports = session;
```

I have checked and confirmed that my environment variables all show up appropriately as they should.

Here is what my knexfile is:

```javascript
    const path = require('path');
    require('dotenv').config({ path: path.join(__dirname, '.env.development') });

    const dbMode = 
       process.env.VITE_ENV === 'development' ? {
        client: "pg",
        connection: {
          host: 'localhost',
          port: 5432,
          user: process.env.VITE_DB_USER,
          password: process.env.VITE_DB_PASS,
          database: process.env.VITE_DB_NAME,
          charset: 'utf8'
        },
        migrations: {
          directory: './server/db/migrations',
          tableName: "knex_migrations"
        },
        seeds: {
          directory: './server/db/seeds'
        }
      } : {
        client: "pg",
        connection: process.env.DATABASE_URL,
        ssl: { require: true }
    }

    module.exports = dbMode;
```

Finally, here is what my server file looks like:

```javascript
    const express = require('express');
    const path = require('path');
    const PORT = process.env.PORT || 5000;
    const app = express();
    const cors = require('cors');
    const session = require('./db/session');
    require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
    const { passport } = require('./passport');

    app.use(cors({
        origin: process.env.VITE_CORS_ORIGIN,
        credentials: true
    }));

    app.use(express.json());
    app.use(express.urlencoded({ extended: false }));
    app.use(session);

    app.use(passport.initialize());
    app.use(passport.session());

    // Skipping some code which I'm pretty sure isn't relevant

    app.listen(PORT, () => {
        console.log(`Listening on port ${PORT}`)
    });
```

I'd really appreciate someone's thoughts on what is the cause of this message and what I can change in my code in order to prevent my session store from failing. I have used code very similar to this in the past with connect-pg-simple and had no problem, though in the past I used Sequelize as opposed to Knex.js.

EDIT 16:37 28/05/2022:

By uninstalling connect-pg-simple and replacing it with an alternative targeted explicitly at Knex.js (namely connect-session-knex) I got my session store to work properly. I imagine connect-pg-simple must have some kind of compatibility issue with Knex.js.

**Comment by voxpelli** [comment]
I clarified the documentation of what the `conObject` should contain: https://github.com/voxpelli/node-connect-pg-simple#connection-options

For your case it would be:

```javascript
{
    host: 'localhost',
    port: 5432,
    user: process.env.VITE_DB_USER,
    password: process.env.VITE_DB_PASS,
    database: process.env.VITE_DB_NAME
}
```

So you're simply sending it the wrong configuration.
