### ISSUE TITLE
Failed to prune sessions: relation "session" does not exist

### ISSUE THREAD

**Issue by dan-ling** [voxpelli/node-connect-pg-simple#254]
Hey, Im working with sails js and i cant seem to get the sessions to work correctly. Im use a postgres DB to store data and that works fine. However the session are not being saved, but they are being created and sent to the browser. 

Iv tried every way to connect, pool; conObject and conString but every time it says 
`Failed to prune sessions: relation “session” does not exist.`
I get the same error when i try to hit an endpoint. 
`error: Error occurred in session middleware :: 'error: relation "session" does not exist`

I have tested the connection by using the pool connection and selecting the table names, and the session table is there. Heres an example of the code im using. 

``` javascript
const { Pool } = require('pg');
const expressSession = require('express-session');
const pgSession = require('connect-pg-simple')(expressSession);

...

const pgPool = new Pool({
  connectionString: ‘<connectionString>’,
  ssl: {
    sslmode: ‘require’,
  }
});

...

  session: {
    adapter: ‘connect-pg-simple’,
    store:  new pgSession({
      pool: pgPool,
      tableName: ‘session’
    }),
    secret: ‘shhhhhhh’,
    cookie: {
      secure: true,
      maxAge: 24 * 60 * 60 * 1000,  // 24 hours
    },
    resave: true,
    saveUninitialized: true
  }
```
Any help would be great! Thank you

**Comment by dan-ling** [comment]
Still struggling to get this to work, Any ideas?

**Comment by headkaze** [comment]
**Once npm installed the module, you need to create the *"session"* table in your database.**

For that you can use the [table.sql](https://github.com/voxpelli/node-connect-pg-simple/blob/main/table.sql) file provided with the module:

`psql mydatabase < node_modules/connect-pg-simple/table.sql`

**Comment by voxpelli** [comment]
You can also do:

```javascript
    store:  new pgSession({
      pool: pgPool,
      tableName: ‘session’,
      createTableIfMissing: true,
    }),
```

See the README here: https://github.com/voxpelli/node-connect-pg-simple#other-options

It should work even better now that #285 is merged.

Closing for now, please comment if anything else is unclear and I can reopen. Sorry for being so slow to respond, my paid assignments took all of my time and I currently [can not afford](https://github.com/sponsors/voxpelli) to turn paid work down.
