### ISSUE TITLE
Unexpected token in node_module index.js

### ISSUE THREAD

**Issue by mbiggs2334** [voxpelli/node-connect-pg-simple#274]
```
node_modules/connect-pg-simple/index.js:235
    #getPruneDelay () {
                   ^

SyntaxError: Unexpected token '('
```

Getting the above error when trying to use the code below.
`const pgSession = require('connect-pg-simple')(session);`

Any way to solve this?

**Comment by voxpelli** [comment]
Which version of node.js? It works in the tests?

**Comment by mbiggs2334** [comment]
Yup, my mistake, Using an older version of Node. All good now. Thank you for the help.
