### ISSUE TITLE
publish patch to npm

### ISSUE THREAD

**Issue by focusaurus** [voxpelli/node-connect-pg-simple#28]
It's been a few months since 76af3367da1a7c114d1d5d29af302d9c779d05bc landed so I guess things are pretty stable. If you wouldn't mind releasing a patch release to npm for that, it would remove some warnings from my CI build scripts. Very low priority - just if you have a chance.

**Comment by voxpelli** [comment]
:+1:, absolutely. I'm just about to add support for [store.touch()](https://github.com/expressjs/session#storetouchsid-session-callback) as well so I'll publish a new minor with both commits later today.

**Comment by voxpelli** [comment]
@focusaurus I've published `3.1.0` to npm then.

If you have any opinions or thoughts on the new `resave: false` compatibility that `store.touch()` adds, then let me know. I'm right now migrating some applications to Express 4, long overdue, and came across that option when moving to the Express 4 session middleware. Feels like something that everyone using this module should be using.

**Comment by focusaurus** [comment]
Great, thanks. I agree that `resave: false` makes sense now that this package supports `store.touch()`.
