### ISSUE TITLE
Property "replaceAll" does not exist on type "string".

### ISSUE THREAD

**Issue by akashdeep931** [voxpelli/node-connect-pg-simple#291]
Having the following type error when deploying my node app on render:

<img width="1029" alt="issue 1" src="https://github.com/voxpelli/node-connect-pg-simple/assets/122111854/3a781fa6-1531-4fc5-8b1f-799db1e5f78e">

The error is on the index.js file, you can see it in the following screenshot:

<img width="1093" alt="issue 2" src="https://github.com/voxpelli/node-connect-pg-simple/assets/122111854/573e6b7d-b541-444f-9cde-91347552e23c">

**Comment by voxpelli** [comment]
@akashdeep931 I’m regards to types, be sure to include `es2021` or later in your TS `lib`, see eg: https://github.com/voxpelli/tsconfig/blob/ce084294e9ecf2f9497fc74bc09404a9315bfc05/node16.json#L8

**Comment by akashdeep931** [comment]
Thank @voxpelli, in my machine it worked perfectly, however render was using an older version of node. I am now using Railway.app for hosting and all is working well.

**Comment by voxpelli** [comment]
@akashdeep931 Great to hear!
