### ISSUE TITLE
Session not set immediately after login

### ISSUE THREAD

**Issue by jmeas** [voxpelli/node-connect-pg-simple#31]
I'm using this library with `express-session`, `passport`, and the Passport Google OAuth2.0 lib. When the user approves of logging in and gets redirected, `req.user` is not set (nor, say, `req.session.passport.user`). I send this info over to the client, so that they know who is logged in. Because it isn't sent, the client believes that the user has not logged in, and redirects them *back* to the login page. If the user then refreshes that page, things are set at that time, and they are considered logged in.

The cookie is set, but the presence of the cookie isn't very reliable. For instance, when they're logged out, the cookie currently sticks around.

I set this app by following [this example](https://github.com/passport/express-4.x-facebook-example/blob/master/server.js), using the in-memory session. The user was set immediately on being redirected. When I refactored to add in this lib, it no longer worked the same way.

Is this an issue anyone else has run into before? I've tried switching around the `resave` and `saveUnitialized` options to see if those would affect this, but with no luck.

The code is pretty awful – I'm trying to get it to work before refactoring – but you can see the configuration [here](https://github.com/jmeas/finance-app/blob/google-sign-in/server/app.js).

===

Results of the investigation:

- It's also lagging behind when the user gets logged out. After hitting the `/logout` endpoint, they're sent the user info until they refresh. **Update:** calling `req.session.destroy` explicitly fixed this. Full code at the end of this post.

- Switching to `pg` rather than `pg-promise` did not solve the issue

- Switching from multiple to a single process didn't fix it either

##### Logout code

Simply calling `req.logout()` wasn't working. Explicitly calling `req.session.destroy()`, on the other hand, forces the session to be destroyed 100% of the time.

```js
app.get('/logout', (req, res) => {
  req.logout();
  req.session.destroy(function (err) {
    res.redirect('/login');
  });
});
```

**Comment by voxpelli** [comment]
This is not something I've experienced and not something I can remember that I've heard anyone else report either.

The method that sets the session `PGStore.prototype.set()` doesn't call the supplied callback until the session has been successfully saved which means that the session module shouldn't continue with the request/response until everything has been saved properly.

I'm also using this with Passport and with OAuth 2 based Passport-flows (GitHub). Here's an example of my code if that helps:

Passport code: https://github.com/voxpelli/node-one-page/blob/726b530e89cf3bcc5c0c9f1f31f52b1a26ed87e5/lib/utils/passportify.js
File that includes session code + above passport code: https://github.com/voxpelli/node-one-page/blob/726b530e89cf3bcc5c0c9f1f31f52b1a26ed87e5/lib/admin.js

**Comment by jmeas** [comment]
Thanks for the links! I'll check them out and see if I can figure anything out.

**Comment by jmeas** [comment]
Still investigating. It's also lagging behind when the user gets logged out. After hitting the `/logout` endpoint, they're sent the user info until they refresh.

**Comment by voxpelli** [comment]
Have you tried creating a similar standalone setup and seen if you can reproduce the behavior there? I know it can take some time, but it could perhaps help pinpoint what could be the cause of this issue.

(I'm unfortunately a bit short on time these upcoming weeks so a bit limited in the time I can spend to debug this myself)

**Comment by jmeas** [comment]
Thanks for the suggestion, @voxpelli ! I've begun doing exactly that. It is taking a little time, but I figure it can live on as a more advanced Passport example (if it ends up working), which will be a good resource for others.

**Comment by jmeas** [comment]
If anyone has time to try debugging this, I made an example app that's showing similar-ish problems. It is here: https://github.com/jmeas/advanced-passport-example

To get set up, you'll need to create a `.env` file with these attributes:

```
SESSION_SECRET='any string can go here'
FACEBOOK_CLIENT_ID=...
FACEBOOK_CLIENT_SECRET=...
DB_URL=...
```

You can make a new Facebook app by going [here](https://developers.facebook.com/quickstarts/?platform=web), and I just spin up a new Heroku app whenever I need a quick, throwaway pg db.

The issues with this app are:

1. logging out only worked if i explicitly destroyed the session. I should only need to call `req.logout()`
2. a user can only ever log in a single time with this app, even though the authentication request through facebook succeeds on each subsequent login attempt

I'm feeling like I must be missing something really obvious with how I'm configuring these things...I can't find anyone else with a similar issue! 😛

**Comment by vitaly-t** [comment]
@jmeas 

>Switching to pg rather than pg-promise did not solve the issue

It is not supposed to, there is nothing pg-promise wouldn't do or do differently from pg, it is all the same underneath ;)

**Comment by jmeas** [comment]
Heh, yeah, I didn't expect it to. I was just trying to verify that none of the differences in my own code was responsible for the bugs, however small they may be :)

I'm wondering if these bugs are due to using the profile returned from the service directly, rather than using a user account table in my DB. I was trying to get a halfway version working before adding user accounts, but atm I'm going forward with adding those to see if that fixes it.

**Comment by jmeas** [comment]
Updates on the bug: I've been stepping through Passport, trying to make sense of it. Issue here:

https://github.com/jaredhanson/passport/issues/482

I also opened a SO question:

http://stackoverflow.com/questions/36975133/passport-js-isauthenticated-inconsistent-behavior-false-when-it-should-be-t

I still have reason to believe this is related to my pg config, because going back to the memory store makes everything work as expected (other than, you know, persisting across app reboots and so on).

**Comment by jmeas** [comment]
@vitaly-t the only thing I can think of is if `pg-promise` is somehow coercing these to be async calls, or something...I just don't see how anyone's code could be working given the behavior that I'm seeing if this wasn't the case.

**Comment by vitaly-t** [comment]
@jmeas Coercing? `pg-promise` is fully async, the same as the underlying `pg` library, just exposing the results through promises instead of callbacks. I don't think it affects anything in the way you suspect ;)

**Comment by jmeas** [comment]
> pg-promise is fully async, the same as the underlying pg library, just exposing the results through promises instead of callbacks. I don't think it affects anything in the way you suspect ;)

Ah, okay. That makes sense. The mystery continues, then.

**Comment by yaey** [comment]
@jmeas Any progress with this?

i had similar problems.
the in memory store was working fine, but when i switched to this library, i also got timing problems

In my case i had
```
app.post('/login', passport.authenticate('login', { failureRedirect: '/login' }),
  function(req, res, next) {
      process.nextTick(function() {
          res.redirect('/');
      });
  });
```

the problem was: the post /login authenticated with and got a sessionId,
but the redirect after the authentication caused a new request with a new sessionId
(which was not authenticated)

changing res.redirct("/"), to  res.sendFile(__dirname + '/index.html'); 
solved my problem

**Comment by jmeas** [comment]
I plan to make an example, but I haven't had time. maybe this weekend ✌️

**Comment by jdposthuma** [comment]
I'm experiencing almost the exact same thing. In my app which uses the passportjs session authentication strategy, this is definitely a race condition as events happen in the following order:

> Updating: 0db0eb9a-c3a0-4565-9974-15a48ba23a63
> Fetching...
> Updated: 0db0eb9a-c3a0-4565-9974-15a48ba23a63
> Found: undefined

Not sure how this fix this...

**Comment by jmeas** [comment]
@jdposthuma I think the next step would be to make a simple, reproducible example that clearly demonstrates that the problem is with this library and not any plugins. If you've got time to do that, then great. That can help maintainers of this lib resolve the problem.

That's what I intend to do when I take a look back at this issue, but there are less annoying problems for me to solve in my app so I'm procrastinating, haha.

If you don't have time to make a reproducible example but manage to bypass the problem somehow, you should post an update here! I'm sure it'll help a bunch of people.

**Comment by jdposthuma** [comment]
I've found a workaround.

When passport.js tries to read a variable from the session to deserialize it, express-session makes an call to the db being used to hydrate the user object (req.user). However, control gets passed to the next handler somehow when reading the value for req.session.user.

The workaround is to fetch the user explicitly from the store (which waits for the data to be returned from the database before passing control to the next handler) and hydrate the user object manually. Place the following middleware before passport.js and you're off the the races:

```
app.use(function (req, res, next) {
  req.sessionStore.get(req.sessionID, function (err, mySession) {
    if (mySession && mySession.passport && mySession.passport.user) {
      db.users.find(mySession.passport.user, function (err, user) {
        req.user = user;
        next();
      });
    } else {
      next();
    }
  });
});
```

I know this is an ugly hack as well as inefficient, but it gets the job done until this bug can be fixed.

**Comment by jmeas** [comment]
Gonna try this out. If this works, then you are a lifesaver 🙂 thanks!

**Comment by jmeas** [comment]
@jdposthuma just tried that – didn't work for me. I placed it between `app.use(session({ ... }))` and  `app.use(passport.initialize()`. Do you have an example app anywhere showing how you've configured it?

**Comment by jdposthuma** [comment]
Will send example tomorrow.

On Monday, July 4, 2016, James, please <notifications@github.com> wrote:

> @jdposthuma <https://github.com/jdposthuma> just tried that – didn't work
> for me. I placed it between app.use(session({ ... })) and
> app.use(passport.initialize(). Do you have an example app anywhere
> showing how you've configured it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/voxpelli/node-connect-pg-simple/issues/31#issuecomment-230357314>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOfspAtIiut9nDtVyxxH4HrQHRf59cyoks5qSX89gaJpZM4ISiZ1>
> .
>


-- 

*Jason Posthuma*
*Developer*
*303-210-4525*

**Comment by jdposthuma** [comment]
Here's my [app.js](https://gist.github.com/jdposthuma/1d5721df642d8ed569df20d3911f5b66)

**Comment by jmeas** [comment]
For me, the issue turned out that Chrome doesn't wait for the whole response before redirecting. So `express-session`'s attempt to save to the DB wasn't completed before the new request began. You can force it to wait by delaying the call to the redirect until you're sure that the session is saved. In my app, this looked like:

```js
app.get('/auth/google/callback', passport.authenticate('google', redirects),
  function(req, res) {
    // Explicitly save the session before redirecting!
    req.session.save(() => {
      res.redirect('/success');
    })
  });
```
