### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by markstuart** [voxpelli/node-connect-pg-simple#34]
Hi @voxpelli, we are using this library in a client project, and they want license information for our top level dependencies. I can't see any license information in the source or package.json, are you able to advise me or update to reflect your license information?

**Comment by voxpelli** [comment]
@markstuart There is a MIT `license` added in the `package.json`: https://github.com/voxpelli/node-connect-pg-simple/blob/master/package.json#L15

I'll add a `LICENSE` file as well

**Comment by voxpelli** [comment]
A `LICENSE` file has now been added as well: https://github.com/voxpelli/node-connect-pg-simple/blob/master/LICENSE

**Comment by markstuart** [comment]
Thank you so much for your prompt response @voxpelli, I really appreciate it 💯
