### ISSUE TITLE
Allow PG-promise module to be loaded

### ISSUE THREAD

**Issue by MagnumDopus** [voxpelli/node-connect-pg-simple#41]
It would be great if you could pass a pg-promise module as the module used for the session store connection.  That way those of us who rely entirely on pg-promise can utilize the same connection.  

This is similar but different from #32

**Comment by RatchapongT** [comment]
How do people currently use pg-promise with this library? I could not find any example

**Comment by jWilko** [comment]
I've added my approach to using pg-promise and connect-pg-simple together in the [#36 pg-pool support thread](https://github.com/voxpelli/node-connect-pg-simple/issues/36#issuecomment-295185078).

It still adds a hoop to jump through - but feels right to me as a stop-gap until there is a viable solution to promise based queries in the module.

**Comment by voxpelli** [comment]
@MagnumDopus @RatchapongT @jWilko This is now officially supported through a new `pgPromise` configuration object and released as version `4.2.0`

**Comment by vitaly-t** [comment]
**UPDATE**

With version 6.x of [pg-promise] you no longer need any special support, as the the library uses the latest [node-postgres] driver, and exposes the pool object of the [Database] object via property [$pool].

[pg-promise]:https://github.com/vitaly-t/pg-promise
[node-postgres]:https://github.com/brianc/node-postgres
[Database]:http://vitaly-t.github.io/pg-promise/Database.html
[$pool]:http://vitaly-t.github.io/pg-promise/Database.html#$pool

@voxpelli probably worth re-opening the issue for a further upgrade, which should mainly be a simplification :wink:
