### ISSUE TITLE
Interest in ES6 version?

### ISSUE THREAD

**Issue by eugene1g** [voxpelli/node-connect-pg-simple#45]
Would you accept a PR to convert the codebase to ES6, as long as it's fully backward compatible?

**Comment by voxpelli** [comment]
For now I don't see a reason to convert the module to ES6.

While have move to ES6 with many of my other modules and do focus on Node 6.x compatible ES6 in general in my other projects, I think that in this case the simplicity of the module makes it a good case for the "If it ain't broken, don't fix it" kind of thinking – the code as it is has worked well and wouldn't improve that much through an ES6:ification.

Any specific reason you would want to convert it to ES6?

**Comment by eugene1g** [comment]
Nope, no strong reason.

For the PR I wanted to use async/await and flowtype - all of which requires Babel conversion - so figured might as well convert over. But it's definitely not broken so I agree let's not waste energy on that
