### ISSUE TITLE
Support for socket connection string

### ISSUE THREAD

**Issue by TheFive** [voxpelli/node-connect-pg-simple#47]
I am using a socket connection string for database connection
```
socket:/home/thefive/tmp/?db=osmbcdev'
```

Url.parse generates the following:

```
Params parsed  Url {
  protocol: 'socket:',
  slashes: null,
  auth: null,
  host: '',
  port: null,
  hostname: '',
  hash: null,
  search: '?db=osmbcdev',
  query: 'db=osmbcdev',
  pathname: '/home/thefive/tmp/',
  path: '/home/thefive/tmp/?db=osmbcdev',
  href: 'socket:/home/thefive/tmp/?db=osmbcdev' }
```
This leads to the following connection object
```
{ user: undefined,
  password: undefined,
  host: '',
  port: undefined,
  database: 'home' }
```

Which can  not connect to the correct database.

As i am using shared hosting, and am "not allowed" to use postgres on an internal port, but should use sockets, it would be nice, if sockets are still supported.

As a workaround i go back to 3.x and will use the connection object as an alternative.

**Comment by voxpelli** [comment]
In current version you can either specify a conObject property or provide a fully configured pgPool, so it should work for you when using either of those, no?

**Comment by TheFive** [comment]
Yes, this should work. As i have put your installed your update in production (my fault in not testing enough) i will use the go back to get system running with connect-pg-simple again (i now use a file session store).
After that i will use the conObject. (or will have a look at the pg pools).
So this is really a minor issue.

**Comment by voxpelli** [comment]
`5.0.0` supports connection strings again
