### ISSUE TITLE
Query every min.

### ISSUE THREAD

**Issue by gilamran** [voxpelli/node-connect-pg-simple#49]
According to the code, every min. there's a query to the db , deleting all the `pruneSessions`
Is that really needed?

**Comment by voxpelli** [comment]
It might or might not be – see #13 regarding why it is the way it is.

Depending on ones needs the pruning time is configurable through `pruneSessionInterval`. It is also possible to disable the automatic pruning completely by setting that `false` – one can then opt to use whatever mechanism one likes to call `pruneSessions`.

**Comment by gilamran** [comment]
thanks!
